version: "3"

services:
  db:
    container_name: ${DATABASE_SERVICE}
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - db-net
      - bridge
    restart: always
    ports: 
      - ${DATABASE_SERVICE_PORT}:5432

  adminer:
    container_name: adminer-container
    image: adminer
    networks:
      - db-net
    ports:
      - 8081:8080

  api:
    container_name: api-container
    build:
      context: ./api
      dockerfile: api.Dockerfile  
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_SERVICE: ${DATABASE_SERVICE}
      DATABASE_SERVICE_PORT: ${DATABASE_SERVICE_PORT}
      FLASK_DEBUG: ${FLASK_DEBUG}
    networks:
      - db-net
      - bridge
    restart: always
    ports: 
     - 5000:5000
    depends_on:
      - db

networks:
  db-net:
  bridge:

volumes:  
  db-data:

