POSTGRES_DB=db
POSTGRES_USER=admin
POSTGRES_PASSWORD=admin
DATABASE_SERVICE=db-container
DATABASE_SERVICE_PORT=5432

SECRET_KEY=secretkey
WTF_CSRF_SECRET_KEY=secretkey2
FLASK_DEBUG=1

build: 
	@ \
	POSTGRES_DB=${POSTGRES_DB} \
	POSTGRES_USER=${POSTGRES_USER} \
	POSTGRES_PASSWORD=${POSTGRES_PASSWORD} \
	DATABASE_SERVICE=${DATABASE_SERVICE} \
	DATABASE_SERVICE_PORT=${DATABASE_SERVICE_PORT} \
	FLASK_DEBUG=${FLASK_DEBUG} \
	SECRET_KEY=${SECRET_KEY} \
	WTF_CSRF_SECRET_KEY=${WTF_CSRF_SECRET_KEY} \
	docker-compose build

up: 
	@ \
	POSTGRES_DB=${POSTGRES_DB} \
	POSTGRES_USER=${POSTGRES_USER} \
	POSTGRES_PASSWORD=${POSTGRES_PASSWORD} \
	DATABASE_SERVICE=${DATABASE_SERVICE} \
	DATABASE_SERVICE_PORT=${DATABASE_SERVICE_PORT} \
	FLASK_DEBUG=${FLASK_DEBUG} \
	SECRET_KEY=${SECRET_KEY} \
	WTF_CSRF_SECRET_KEY=${WTF_CSRF_SECRET_KEY} \
	docker-compose up

down:
	@ \
	docker-compose down
